name: putra_tee
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  url_launcher: ^6.0.12
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  csv: ^5.1.1
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  random_string: ^2.3.1
  location: ^5.0.3
  flutter_svg: ^1.1.0
  sqflite: ^2.0.0+4 # Added sqflite for SQLite database operations
  mysql1: ^0.20.0
  mysql_client: ^0.0.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/route1.png
    - assets/images/route2.png
    - assets/images/route3.png
    - assets/images/route4.png
    - assets/images/route5.png
    - assets/images/arrow_icon.png
    - assets/images/bus_stop_icon.png
    - assets/images/p_logo.png
    - assets/images/transit_map.png
    - assets/images/putra-t-sidebar-logo.png
    - assets/images/academy.jpg
    - assets/images/asper.jpg
    - assets/images/banquet.JPG
    - assets/images/central.JPG
    - assets/images/fbmk.JPG
    - assets/images/fbsb.JPG
    - assets/images/fp.JPG
    - assets/images/fpc.JPG
    - assets/images/frsb.JPG
    - assets/images/fs.JPG
    - assets/images/fsktm.JPG
    - assets/images/fstm.JPG
    - assets/images/ibs.JPG
    - assets/images/inspem.JPG
    - assets/images/k10.JPG
    - assets/images/k14.jpg
    - assets/images/kmb.JPG
    - assets/images/ktag.JPG
    - assets/images/pfc.JPG
    - assets/images/psas.JPG
    - assets/images/sfc.JPG
    - assets/images/sgs.JPG
    - assets/images/kaa.JPG
    - assets/images/campus-map-south.jpeg
    - assets/images/campus-map-north.jpeg
    - assets/images/bus_location_tracker.png
    - assets/images/bus_stop_marker.png
    - assets/images/my-location.png
    - assets/images/driver/driver-1000.png
    - assets/images/driver/driver-1010.png
    - assets/images/driver/driver-1020.png
    - assets/images/driver/driver-1030.png
    - assets/images/driver/driver-1040.png
    - assets/images/driver/driver-1050.png
    - assets/images/route1-nav-high.png
    - assets/images/route1-nav-medium.png



flutter_native_splash:
  image: "assets/images/putra-t-splash-logo.png"
